<?php

namespace Database\Seeders;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $products = array(
            array('id' => '1','name' => 'Mouse','code' => '63920719','type' => 'standard','barcode_symbology' => 'C39','brand_id' => '4','category_id' => '3','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '320','price' => '400','qty' => '0','alert_quantity' => '20','promotion' => '1','promotion_price' => '350','starting_date' => '2020-06-30','last_date' => '2020-07-31','tax_id' => '1','tax_method' => '1','image' => 'toponemouse.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '<p style=@text-align: center;@>11:11:30 AM<img src=@https://pbs.twimg.com/profile_images/900037286879838208/sZhajgua_400x400.jpg@ alt=@lioncoders@ width=@400@ height=@400@ /><span style=@background-color: #ccffff;@>hello world<br /></span></p>','is_active' => '1','created_at' => '2018-05-13 04:23:03','updated_at' => '2021-05-30 13:33:04'),
            array('id' => '2','name' => 'Mango','code' => '72782608','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '1','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '8','price' => '12','qty' => '100','alert_quantity' => '100','promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => '2','tax_method' => '2','image' => 'mango.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-05-13 04:38:31','updated_at' => '2022-04-30 16:19:01'),
            array('id' => '3','name' => 'Earphone','code' => '85415108','type' => 'standard','barcode_symbology' => 'C128','brand_id' => '4','category_id' => '2','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '200','price' => '250','qty' => '100','alert_quantity' => '25','promotion' => NULL,'promotion_price' => '220','starting_date' => '2020-11-02','last_date' => '2020-11-30','tax_id' => NULL,'tax_method' => '1','image' => 'airphonesamsung.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => '0','featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '<p>Earphone with good <strong>sound quality.</strong></p>
<p>jhjkhjkhjh @@</p>','is_active' => '1','created_at' => '2018-05-13 04:39:55','updated_at' => '2022-04-30 16:19:00'),
            array('id' => '4','name' => 'Lychee','code' => '38314290','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '1','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '1','price' => '2','qty' => '0','alert_quantity' => '50','promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'lychee.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '<p style=@text-align: center;@><em>sweet lychee from <strong>kalipur</strong>, bashkhali</em></p>','is_active' => '1','created_at' => '2018-05-24 04:54:56','updated_at' => '2021-02-16 07:09:48'),
            array('id' => '5','name' => 'Baby doll','code' => '31261512','type' => 'standard','barcode_symbology' => 'C128','brand_id' => '3','category_id' => '4','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '100','price' => '120','qty' => '0','alert_quantity' => '50','promotion' => '1','promotion_price' => '100','starting_date' => '2020-02-28','last_date' => '2020-02-29','tax_id' => NULL,'tax_method' => '1','image' => 'lalacrybabydoll.jpg,15992893905761572515542825e4e2e433-e29b-4ca1-abb2-aad995574f2a_1.e4dc9f20c1d8b2999d66556ae0aa1600.jpeg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-05-24 04:58:20','updated_at' => '2021-05-24 19:45:58'),
            array('id' => '6','name' => 'Test','code' => '78041363','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '2','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '12','price' => '21','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => NULL,'is_active' => '0','created_at' => '2018-05-28 05:50:25','updated_at' => '2018-05-28 05:53:24'),
            array('id' => '10','name' => 'Potato','code' => '212132','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '9','unit_id' => '7','purchase_unit_id' => '7','sale_unit_id' => '7','cost' => '10','price' => '22','qty' => '100','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'potato.jpeg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-06-25 07:34:53','updated_at' => '2022-04-30 16:19:00'),
            array('id' => '13','name' => 'Product One','code' => '40624536','type' => 'digital','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '3','unit_id' => '0','purchase_unit_id' => '0','sale_unit_id' => '0','cost' => '0','price' => '21','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'ldms.jpg','file' => '1532330693.JPG','is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '<p>Amazon Prime 1 Month<br />Price: 300tk</p>
<p>User Ability: Max 2 Mobile User<br />Duration: 1 Month<br />Package: Premium</p>','is_active' => '1','created_at' => '2018-07-23 07:09:29','updated_at' => '2020-03-07 22:45:01'),
            array('id' => '14','name' => 'Product Two','code' => '40237871','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '9','unit_id' => '8','purchase_unit_id' => '8','sale_unit_id' => '8','cost' => '55','price' => '56','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-08-01 04:36:51','updated_at' => '2018-08-01 04:41:48'),
            array('id' => '15','name' => 'Product Three','code' => 'awd','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '1','unit_id' => '4','purchase_unit_id' => '4','sale_unit_id' => '4','cost' => '312','price' => '132','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-08-05 07:26:19','updated_at' => '2018-08-05 07:27:03'),
            array('id' => '16','name' => 'Product Four','code' => 'eqw','type' => 'digital','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '2','unit_id' => '0','purchase_unit_id' => '0','sale_unit_id' => '0','cost' => '0','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => '1533454125.jpg','is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-08-05 07:28:45','updated_at' => '2018-08-05 07:29:23'),
            array('id' => '17','name' => 'Product Five','code' => 'wer','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '2','unit_id' => '4','purchase_unit_id' => '4','sale_unit_id' => '4','cost' => '12','price' => '21','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-08-06 10:25:43','updated_at' => '2018-08-06 10:27:41'),
            array('id' => '18','name' => 'Product Six','code' => 'wre','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '1','unit_id' => '4','purchase_unit_id' => '4','sale_unit_id' => '4','cost' => '3','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-08-06 10:45:42','updated_at' => '2018-08-06 10:57:41'),
            array('id' => '19','name' => 'Product Seven','code' => 'wer','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '2','unit_id' => '4','purchase_unit_id' => '4','sale_unit_id' => '4','cost' => '3','price' => '23','qty' => '0','alert_quantity' => NULL,'promotion' => '1','promotion_price' => NULL,'starting_date' => '2018-08-06','last_date' => '2018-08-10','tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-08-06 11:41:46','updated_at' => '2019-11-28 11:16:47'),
            array('id' => '20','name' => 'Egg','code' => '4234','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '10','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '1','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-08-29 05:37:07','updated_at' => '2018-08-29 05:43:18'),
            array('id' => '21','name' => 'Big Egg','code' => '1','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '11','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '1','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-08-29 05:49:27','updated_at' => '2018-08-29 05:53:21'),
            array('id' => '22','name' => 'iphone-X','code' => '97103461','type' => 'standard','barcode_symbology' => 'C128','brand_id' => '5','category_id' => '2','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '800','price' => '1000','qty' => '0','alert_quantity' => '20','promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => '1','tax_method' => '1','image' => 'iphoneX.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-09-03 10:05:17','updated_at' => '2021-02-17 07:32:38'),
            array('id' => '23','name' => 'Product Seven','code' => '1237920612311a','type' => 'standard','barcode_symbology' => 'C39','brand_id' => NULL,'category_id' => '2','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '1','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-09-11 05:53:18','updated_at' => '2018-09-11 05:56:04'),
            array('id' => '24','name' => 'chocolate','code' => '84802317','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '9','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '1','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => NULL,'file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-09-16 03:42:01','updated_at' => '2018-09-16 04:10:43'),
            array('id' => '25','name' => 'Galaxy S9','code' => '72100265','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '2','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '500','price' => '1000','qty' => '0','alert_quantity' => '50','promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => '1','tax_method' => '1','image' => 'SamsungGalaxyS9.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-10-23 07:13:22','updated_at' => '2021-02-16 07:09:48'),
            array('id' => '26','name' => 'Samsung Set','code' => '39053411','type' => 'combo','barcode_symbology' => 'C128','brand_id' => '4','category_id' => '2','unit_id' => '0','purchase_unit_id' => '0','sale_unit_id' => '0','cost' => '0','price' => '1250','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => '3,25','qty_list' => '1,1','price_list' => '250,1000','product_details' => '','is_active' => '1','created_at' => '2018-11-19 09:59:06','updated_at' => '2018-11-20 08:12:02'),
            array('id' => '27','name' => 'mixed fruit juice','code' => '24805187','type' => 'combo','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '9','unit_id' => '0','purchase_unit_id' => '0','sale_unit_id' => '0','cost' => '0','price' => '16','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => '4,2','qty_list' => '3,1','price_list' => '2,10','product_details' => '','is_active' => '0','created_at' => '2018-11-19 15:39:26','updated_at' => '2018-11-25 04:35:51'),
            array('id' => '28','name' => 'Product Eight','code' => 'sasas','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '2','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '2','cost' => '1','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-11-20 10:14:12','updated_at' => '2018-11-20 10:34:02'),
            array('id' => '29','name' => 'Test Cloth','code' => '16055884','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '4','unit_id' => '10','purchase_unit_id' => '10','sale_unit_id' => '10','cost' => '10','price' => '15','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => '2018-11-29','last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '0','created_at' => '2018-11-29 09:49:25','updated_at' => '2019-03-01 21:09:27'),
            array('id' => '30','name' => 'Polo Shirt','code' => '53467102','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '12','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '50','price' => '100','qty' => '0','alert_quantity' => '10','promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'PoloShirt.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-12-05 05:29:43','updated_at' => '2021-02-16 07:09:48'),
            array('id' => '31','name' => 'Shoe','code' => '90471412','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '12','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '250','price' => '300','qty' => '0','alert_quantity' => '10','promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'Shoe.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-12-05 05:33:09','updated_at' => '2021-02-16 07:09:48'),
            array('id' => '32','name' => 'Toothpaste','code' => '859875003032','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '12','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '5','price' => '10','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => '1572759415477product-page-fresh-breath.jpg','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-12-19 05:56:08','updated_at' => '2021-02-16 07:09:48'),
            array('id' => '33','name' => 'tissue','code' => '8941161008066','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '12','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '10','price' => '20','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '0','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2018-12-24 05:33:58','updated_at' => '2020-09-05 13:07:39'),
            array('id' => '48','name' => 'T-shirt','code' => '93475396','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '12','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '2','price' => '3','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => '1577165120189220px-Blue_Tshirt.jpg','file' => NULL,'is_variant' => '1','is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '0','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2019-11-21 13:03:04','updated_at' => '2021-02-16 07:09:48'),
            array('id' => '60','name' => 'testvar','code' => '32081679','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '12','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '1','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => '1','is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '0','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2020-05-18 22:44:14','updated_at' => '2020-10-27 05:42:06'),
            array('id' => '61','name' => 'TV','code' => '32703342','type' => 'standard','barcode_symbology' => 'C128','brand_id' => '4','category_id' => '2','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '3000','price' => '10000','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => '2','tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2020-08-16 21:58:39','updated_at' => '2021-02-17 07:32:38'),
            array('id' => '62','name' => 'Test variant','code' => '81145830','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '4','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '1','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => '1','is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2020-09-27 12:08:27','updated_at' => '2021-02-11 07:28:16'),
            array('id' => '71','name' => 'Napa','code' => '41930312','type' => 'standard','barcode_symbology' => 'C128','brand_id' => NULL,'category_id' => '19','unit_id' => '1','purchase_unit_id' => '1','sale_unit_id' => '1','cost' => '1','price' => '2','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => '1','is_diffPrice' => '0','featured' => '0','product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2021-03-07 14:12:53','updated_at' => '2021-05-30 13:41:19'),
            array('id' => '72','name' => 'Combo One Vat-Inclusive','code' => '02080275','type' => 'combo','barcode_symbology' => 'C128','brand_id' => '3','category_id' => '2','unit_id' => '0','purchase_unit_id' => '0','sale_unit_id' => '0','cost' => '0','price' => '252','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '2','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => '1','product_list' => '2,3','qty_list' => '1,1','price_list' => '12,240','product_details' => '','is_active' => '1','created_at' => '2022-04-30 06:00:19','updated_at' => '2022-04-30 06:00:19'),
            array('id' => '73','name' => 'Combo Two Vat Exclusive','code' => '12066278','type' => 'combo','barcode_symbology' => 'C128','brand_id' => '3','category_id' => '2','unit_id' => '0','purchase_unit_id' => '0','sale_unit_id' => '0','cost' => '0','price' => '420','qty' => '0','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => NULL,'last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => NULL,'is_diffPrice' => NULL,'featured' => NULL,'product_list' => '1,10','qty_list' => '1,1','price_list' => '390,30','product_details' => '','is_active' => '1','created_at' => '2022-04-30 06:50:58','updated_at' => '2022-04-30 06:50:58'),
            array('id' => '74','name' => 'Batch Product 1','code' => '30402390','type' => 'standard','barcode_symbology' => 'C128','brand_id' => '7','category_id' => '12','unit_id' => '1','purchase_unit_id' => '2','sale_unit_id' => '1','cost' => '100','price' => '150','qty' => '1200','alert_quantity' => NULL,'promotion' => NULL,'promotion_price' => NULL,'starting_date' => '2022-04-30','last_date' => NULL,'tax_id' => NULL,'tax_method' => '1','image' => 'zummXD2dvAtI.png','file' => NULL,'is_variant' => NULL,'is_batch' => '1','is_diffPrice' => NULL,'featured' => NULL,'product_list' => NULL,'qty_list' => NULL,'price_list' => NULL,'product_details' => '','is_active' => '1','created_at' => '2022-04-30 17:43:24','updated_at' => '2022-04-30 17:44:27')
        );
        Product::insert($products);
    }
}
