import { MD3LightTheme } from 'react-native-paper';

export const blackWhiteTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#000000',
    onPrimary: '#ffffff',
    primaryContainer: '#000000',
    onPrimaryContainer: '#ffffff',
    secondary: '#000000',
    onSecondary: '#ffffff',
    secondaryContainer: '#f2f2f2',
    onSecondaryContainer: '#000000',
    tertiary: '#000000',
    onTertiary: '#ffffff',
    background: '#ffffff',
    onBackground: '#000000',
    surface: '#ffffff',
    onSurface: '#000000',
    surfaceVariant: '#f2f2f2',
    onSurfaceVariant: '#333333',
    outline: '#000000',
    outlineVariant: '#d9d9d9',
    error: '#000000',
    onError: '#ffffff',
    errorContainer: '#f2f2f2',
    onErrorContainer: '#000000',
    inverseSurface: '#000000',
    inverseOnSurface: '#ffffff',
    inversePrimary: '#ffffff',
    backdrop: 'rgba(0, 0, 0, 0.45)',
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: 'transparent',
      level1: '#ffffff',
      level2: '#ffffff',
      level3: '#ffffff',
      level4: '#ffffff',
      level5: '#ffffff',
    },
  },
};
